### ISSUE TITLE
PHP Fatal error:  Uncaught Psr\Log\InvalidArgumentException: You must provide an instance of \Yiisoft\Log\Target.

### ISSUE THREAD

**Issue by razonyang** [yiisoft/yii-base-cli#7]
It is because of the logger configuration:

```php
    'logger' => [
        '__construct()' => [
            'targets' => [
                [
                    '__class' => Yiisoft\Log\FileTarget::class,
                    'levels'  => ['error', 'warning'],
                ],
            ],
        ],
    ],
```

The `targets` is an array that contains target's definition, but `Logger::setTarget` expects target as an instance of `Target`:
https://github.com/yiisoft/log/blob/8e5245d2e4606a6d565e94c1d42bd1d1c1dd9990/src/Logger.php#L119

What is the best/proper way to make it works? It doesn't seem reasonable that `log` package take the responsibility to handle target's definition, since `log` doesn't depends on `di` and `yii-core` like [Cache::setHandler](https://github.com/yiisoft/cache/blob/d4138d728324695c164c0bad5bef7ba467ccd91a/src/Cache.php#L93).

Should I initialize target instances in the configuration file?

### What steps will reproduce the problem?
```
./vendor/bin/yii hello
```

### What's expected?

hello world

### What do you get instead?

PHP Fatal error:  Uncaught Psr\Log\InvalidArgumentException: You must provide an instance of \Yiisoft\Log\Target. in /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/log/src/Logger.php:120
Stack trace:
#0 /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/log/src/Logger.php(82): Yiisoft\Log\Logger->setTargets(Array)
#1 [internal function]: Yiisoft\Log\Logger->__construct(Array)
#2 /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/di/src/AbstractContainer.php(358): ReflectionClass->newInstanceArgs(Array)
#3 /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/di/src/AbstractContainer.php(189): yii\di\AbstractContainer->buildFromConfig('logger', Array)
#4 /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/di/src/AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition('logger', Array, Array)
#5 /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/di/src/Container.php(55): yii\di\AbstractContainer->build('logger')
#6 /home/razon/Projects/razonyang/yii-base-cli/vendor in /home/razon/Projects/razonyang/yii-base-cli/vendor/yiisoft/log/src/Logger.php on line 120

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0@dev
| PHP version      | 7.3.5
| Operating system | ArchLinux

**Comment by samdark** [comment]
@machour is it connected with recent log changes?

**Comment by machour** [comment]
Yes it is. @razonyang the problem is that DI doesn't look recursively into the __construct() array to construct things.

Here's how I'm doing it at the moment (and it's ugly):

```php
    'logger' => static function (\yii\di\Container $container) {
        /** @var \yii\base\Aliases $aliases */
        $aliases = $container->get('aliases');
        $fileTarget = new Yiisoft\Log\FileTarget($aliases->get('@runtime/logs/app.log'),  $container->get('file-rotator'));
        return new \Yiisoft\Log\Logger([
            'file' => $fileTarget->setCategories(['application']),
        ]);
    },
```

**Comment by samdark** [comment]
I think https://github.com/yiisoft/di/pull/76 may fix it.

**Comment by machour** [comment]
Not so sure, see conversation https://github.com/yiisoft/di/pull/76#discussion_r277604659
